SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE   VIEW [bds].[SD_CLIENTES_VTA_VALES_MEDI]
AS
SELECT DISTINCT
       TRIM(NIF) AS NIFSCV
      ,TRIM(CODCLIENTE) AS CODCLIENTE
      ,TRIM(NOMBRE) AS NOMBRE
      ,TRIM(TRATAMIENTO) AS TRATAMIENTO
      ,TRIM(CALLE) AS CALLE
      ,TRIM(DISTRITO) AS DISTRITO
      ,TRIM(CODPOSTAL) AS CODPOSTAL
      ,TRIM(TELEFONO) AS TELEFONO
      ,TRIM(RUBRO) AS RUBRO  
FROM stg.SD_KNA1 AS k
INNER JOIN stg.SD_VBRK AS v
  ON v.CLIENTEPAGADOR = k.CODCLIENTE
GO