CREATE TABLE [stg].[RE_VIBDRO] (
  [Clave RE] [varchar](50) NULL,
  [Sociedad] [varchar](50) NULL,
  [Unidad económica] [varchar](50) NULL,
  [Objeto de alquiler] [varchar](50) NULL,
  [Nº objeto] [varchar](50) NULL,
  [Clv.bien.inmb.] [varchar](50) NULL,
  [Clase activo fijo] [varchar](50) NULL,
  [Autor] [varchar](50) NULL,
  [Primer registro] [varchar](50) NULL,
  [Hora primera entrada] [varchar](50) NULL,
  [Origen 1ª entrada] [varchar](50) NULL,
  [Modificado por] [varchar](50) NULL,
  [Último tratamiento] [varchar](50) NULL,
  [Hora último tratam.] [varchar](50) NULL,
  [Origen del tratamiento] [varchar](50) NULL,
  [Responsable] [varchar](50) NULL,
  [Autorización modif.] [varchar](255) NULL,
  [Grupo autoriz.] [varchar](255) NULL,
  [Objeto válido desde] [varchar](50) NULL,
  [Objeto válido hasta] [varchar](50) NULL,
  [Tipo objeto alquiler] [varchar](50) NULL,
  [Clase de uso] [varchar](50) NULL,
  [Denom.obj.alquiler] [varchar](50) NULL,
  [Terreno] [varchar](255) NULL,
  [Edificios] [varchar](50) NULL,
  [Nº unidad de alquiler obsoleto] [varchar](50) NULL,
  [Posible us.comunit.] [varchar](255) NULL,
  [Fe.in.flj.financiero] [varchar](50) NULL,
  [Primer uso] [varchar](50) NULL,
  [Fecha: Subarriendo] [varchar](50) NULL,
  [Fecha: Reserv.desde] [varchar](50) NULL,
  [Fecha: Reserv.hasta] [varchar](50) NULL,
  [Ala de edificio] [varchar](50) NULL,
  [Categ.equipamiento] [varchar](255) NULL,
  [Clase de ubicación] [varchar](255) NULL,
  [Recargo/reducc.(%)] [varchar](50) NULL,
  [Cálculo alq.base] [varchar](255) NULL,
  [Clasif.LIA porcent.] [varchar](50) NULL,
  [Incremento (%)] [varchar](50) NULL,
  [Causa desviación] [varchar](255) NULL,
  [Ubicación en planta] [varchar](255) NULL,
  [Número de ubicación] [varchar](255) NULL,
  [Propiedad privada] [varchar](255) NULL,
  [Planta] [varchar](50) NULL,
  [Planta hasta] [varchar](50) NULL,
  [Fecha reformas] [varchar](50) NULL,
  [FF archivado hasta] [varchar](50) NULL,
  [FF fijo hasta] [varchar](50) NULL,
  [1ª contabil.desde] [varchar](50) NULL,
  [P.liquid.gast.adic.] [varchar](255) NULL,
  [Lt.ind.alquileres] [varchar](255) NULL,
  [LstIndAlq utilizada] [varchar](255) NULL,
  [Año de construcción] [varchar](50) NULL,
  [Moneda] [varchar](255) NULL,
  [Propiedad comunit.] [varchar](255) NULL,
  [Bloqueado p.oferta] [varchar](255) NULL,
  [Región] [varchar](255) NULL,
  [Región1] [varchar](255) NULL,
  [Región2] [varchar](255) NULL,
  [Function] [varchar](50) NULL,
  [Function Name] [varchar](50) NULL,
  [EDID] [varchar](50) NULL,
  [EGID] [varchar](50) NULL,
  [Floor] [varchar](50) NULL,
  [Location on Floor] [varchar](255) NULL,
  [EWID] [varchar](50) NULL,
  [Cooking Facilities] [varchar](50) NULL,
  [Admin. Dwelling Number] [varchar](255) NULL,
  [Door Number] [varchar](255) NULL,
  [Dwelling Status] [varchar](50) NULL,
  [Year of Demolition] [varchar](50) NULL,
  [Number of Rooms] [varchar](50) NULL,
  [Floor Area in M2] [varchar](50) NULL,
  [UsageType] [varchar](50) NULL,
  [Distrito reg.prop.] [varchar](255) NULL,
  [Prop. Taxable Value] [varchar](50) NULL,
  [Moneda1] [varchar](255) NULL,
  [Conservation Level] [varchar](255) NULL
)
ON [PRIMARY]
GO