CREATE TABLE [stg].[RE_VICNCN] (
  [Clave RE] [varchar](50) NULL,
  [Sociedad] [varchar](50) NULL,
  [Contrato] [varchar](50) NULL,
  [Nº objeto] [varchar](50) NULL,
  [Clv.bien.inmb.] [varchar](50) NULL,
  [Clase activo fijo] [varchar](50) NULL,
  [Autor] [varchar](50) NULL,
  [Primer registro] [varchar](50) NULL,
  [Hora primera entrada] [varchar](50) NULL,
  [Origen 1ª entrada] [varchar](50) NULL,
  [Modificado por] [varchar](50) NULL,
  [Último tratamiento] [varchar](50) NULL,
  [Hora último tratam.] [varchar](50) NULL,
  [Origen del tratamiento] [varchar](50) NULL,
  [Responsable] [varchar](50) NULL,
  [Autorización modif.] [varchar](255) NULL,
  [Grupo autoriz.] [varchar](255) NULL,
  [Clase de contrato] [varchar](50) NULL,
  [Inicio contrato] [varchar](50) NULL,
  [Fin per.vigencia] [varchar](50) NULL,
  [Denominación de contrato] [varchar](100) NULL,
  [Activo desde] [varchar](50) NULL,
  [Derecho arrendamien.] [varchar](50) NULL,
  [Contrato anterior] [varchar](50) NULL,
  [Sociedad p.contrato pral.] [varchar](50) NULL,
  [ContratoPral] [varchar](50) NULL,
  [Moneda del contrato] [varchar](50) NULL,
  [Sector industrial] [varchar](50) NULL,
  [Relevante para VN] [varchar](50) NULL,
  [Clase de fianza] [varchar](255) NULL,
  [Cierre de contrato] [varchar](50) NULL,
  [2ª firma digital] [varchar](50) NULL,
  [Fe.in.flj.financiero] [varchar](50) NULL,
  [Primer fin contrato] [varchar](50) NULL,
  [Rescisión el] [varchar](50) NULL,
  [Fecha de entrada] [varchar](50) NULL,
  [Motivo de rescisión] [varchar](50) NULL,
  [Rescisión activ.el] [varchar](50) NULL,
  [FF archivado hasta] [varchar](50) NULL,
  [FF fijo hasta] [varchar](50) NULL,
  [1ª contabil.desde] [varchar](50) NULL,
  [UnidadEconómicaContr] [varchar](50) NULL,
  [Traspaso propiedades] [varchar](50) NULL,
  [Fin trsp.propiedades] [varchar](50) NULL,
  [Multiple Assignment] [varchar](50) NULL,
  [Possession Date From] [varchar](50) NULL,
  [Possession Date To] [varchar](50) NULL,
  [Relevant to Security Deposit] [varchar](255) NULL,
  [No Sec.Dep. Data Change] [varchar](255) NULL
)
ON [PRIMARY]
GO